rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

spring:
  data:
    mongodb:
      uri: mongodb+srv://9mohapx9:root@cluster0.lclzzko.mongodb.net/test-task
jwt:
  issuer: https://amazonagency.com
  valid-for-days: 30
mongo:
  source:
    path: classpath:report.json
